#!/usr/bin/env bash
#
# Install Onset Review on Ubuntu.
#
# What this does, in order:
#   1. installs the system libraries Qt needs (apt, needs sudo once),
#   2. builds a virtual environment under ~/.local/share/onset-review,
#   3. installs this checkout into it with the `review` extra,
#   4. puts an `onset-review` command on PATH and an entry in the
#      applications menu.
#
# What it deliberately does not do: touch the system Python, install anything
# outside the user's home beyond the apt packages, or fetch any recording. A
# reviewer gets a working window and no data; `--with-sample` adds one minute
# of one public patient so the first launch has something to open.
#
# Usage:
#   ./packaging/install-ubuntu.sh [--with-sample] [--prefix DIR] [--no-apt]
#   ./packaging/install-ubuntu.sh --uninstall
#
set -euo pipefail

PREFIX="${HOME}/.local/share/onset-review"
BIN_DIR="${HOME}/.local/bin"
DESKTOP_DIR="${HOME}/.local/share/applications"
ICON_DIR="${HOME}/.local/share/icons/hicolor/scalable/apps"
WITH_SAMPLE=0
RUN_APT=1
UNINSTALL=0

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Qt 6 on a server or minimal desktop install is missing most of these. The
# list is what PySide6's QtWidgets, its xcb platform plugin and its offscreen
# plugin actually dlopen; a missing one surfaces as "could not load the Qt
# platform plugin xcb", which says nothing about which library is absent.
APT_PACKAGES=(
  python3-venv python3-pip
  libegl1 libgl1 libglib2.0-0
  libxkbcommon-x11-0 libxcb-cursor0 libxcb-icccm4 libxcb-keysyms1
  libxcb-shape0 libxcb-xinerama0 libxcb-randr0 libxcb-render-util0
  libdbus-1-3 libfontconfig1 libfreetype6
)

say()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m==>\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m==>\033[0m %s\n' "$*" >&2; exit 1; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --with-sample) WITH_SAMPLE=1; shift ;;
    --no-apt)      RUN_APT=0; shift ;;
    --prefix)      PREFIX="$2"; shift 2 ;;
    --uninstall)   UNINSTALL=1; shift ;;
    -h|--help)     sed -n '2,30p' "$0"; exit 0 ;;
    *)             die "unknown option: $1 (try --help)" ;;
  esac
done

if [[ "${UNINSTALL}" == "1" ]]; then
  say "Removing Onset Review"
  rm -rf "${PREFIX}"
  rm -f "${BIN_DIR}/onset-review" \
        "${DESKTOP_DIR}/onset-review.desktop" \
        "${ICON_DIR}/onset-review.svg"
  command -v update-desktop-database >/dev/null \
    && update-desktop-database "${DESKTOP_DIR}" 2>/dev/null || true
  say "Removed. The apt packages and any cached recordings were left alone."
  exit 0
fi

# -- 0. sanity ---------------------------------------------------------------
[[ -f "${HERE}/pyproject.toml" ]] \
  || die "run this from the onset-hfo checkout (no pyproject.toml at ${HERE})"

PYTHON="$(command -v python3 || true)"
[[ -n "${PYTHON}" ]] || die "python3 not found"
PY_VERSION="$("${PYTHON}" -c 'import sys; print("%d.%d" % sys.version_info[:2])')"
"${PYTHON}" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 10) else 1)' \
  || die "Python 3.10 or newer is required; this is ${PY_VERSION}"
say "Python ${PY_VERSION} at ${PYTHON}"

# -- 1. system libraries -----------------------------------------------------
if [[ "${RUN_APT}" == "1" ]]; then
  say "Installing the system libraries Qt needs (sudo)"
  sudo apt-get update -qq
  sudo apt-get install -y --no-install-recommends "${APT_PACKAGES[@]}"
else
  say "Skipping apt (--no-apt)"
fi

# -- 2. virtual environment --------------------------------------------------
say "Building the environment in ${PREFIX}"
mkdir -p "${PREFIX}"
[[ -x "${PREFIX}/venv/bin/python" ]] || "${PYTHON}" -m venv "${PREFIX}/venv"
VENV_PY="${PREFIX}/venv/bin/python"
"${VENV_PY}" -m pip install --quiet --upgrade pip wheel

# -- 3. the package ----------------------------------------------------------
say "Installing onset-hfo with the desktop reviewer (a few minutes)"
"${VENV_PY}" -m pip install --quiet -e "${HERE}[review]"

say "Checking that Qt can start"
if ! QT_QPA_PLATFORM=offscreen "${VENV_PY}" -c \
      'from qtpy.QtWidgets import QApplication; QApplication([]); print("Qt ok")'; then
  die "Qt could not start. Re-run without --no-apt, or install the libraries listed
in APT_PACKAGES at the top of this script."
fi

# -- 4. command, menu entry, icon -------------------------------------------
say "Installing the launcher"
mkdir -p "${BIN_DIR}" "${DESKTOP_DIR}" "${ICON_DIR}"

# A wrapper rather than a symlink into the venv, so the working directory is
# the checkout: that is where `artifacts/data` lives, and a reviewer launching
# from the applications menu starts in their home directory otherwise and sees
# an empty recording list.
cat > "${BIN_DIR}/onset-review" <<WRAPPER
#!/usr/bin/env bash
# Generated by packaging/install-ubuntu.sh. Re-run that script to update.
cd "${HERE}" || exit 1
exec "${PREFIX}/venv/bin/onset-review" "\$@"
WRAPPER
chmod +x "${BIN_DIR}/onset-review"

install -m 644 "${HERE}/packaging/onset-review.svg" "${ICON_DIR}/onset-review.svg"
sed "s|^Exec=onset-review|Exec=${BIN_DIR}/onset-review|" \
    "${HERE}/packaging/onset-review.desktop" > "${DESKTOP_DIR}/onset-review.desktop"
chmod 644 "${DESKTOP_DIR}/onset-review.desktop"
command -v update-desktop-database >/dev/null \
  && update-desktop-database "${DESKTOP_DIR}" 2>/dev/null || true

# -- 5. a recording to open --------------------------------------------------
if [[ "${WITH_SAMPLE}" == "1" ]]; then
  say "Fetching one minute of sub-01 from OpenNeuro ds003498"
  if ! (cd "${HERE}" && "${VENV_PY}" -m onset_hfo.cli fetch \
          --subject sub-01 --t-start 0 --t-stop 60); then
    SAMPLE_FAILED=1
    warn "the fetch failed -- its own error is above this line. The software is
installed and works; there is just nothing cached to open yet."
  fi
fi

CACHED="$(cd "${HERE}" && "${VENV_PY}" -c \
  'from onset_review.session import cached_windows; print(len(cached_windows()))' \
  2>/dev/null || echo 0)"

say "Done."
echo

# The PATH note comes first. Printing "Launch: onset-review" and only then
# that the directory is not on PATH means the first thing the reader tries is
# the thing that cannot work -- which is exactly what happens when the install
# line ends in `&& onset-review`.
LAUNCH="onset-review"
if ! printf '%s' ":${PATH}:" | grep -q ":${BIN_DIR}:"; then
  LAUNCH="${BIN_DIR}/onset-review"
  warn "${BIN_DIR} is not on your PATH, so plain 'onset-review' will not be
found in this shell. Either use the full path below, or add this to ~/.bashrc
and open a new terminal:"
  echo "    export PATH=\"${BIN_DIR}:\${PATH}\""
  echo
fi

echo "  Launch:      ${LAUNCH}          (or 'Onset Review' in the menu)"
echo "  Cached:      ${CACHED} window(s) ready to open offline"
echo "  List them:   ${LAUNCH} --list"
echo "  Straight in: ${LAUNCH} --subject sub-01 --window 0 60 --expert"
echo
if [[ "${CACHED}" == "0" ]]; then
  # Never advise re-running the flag that has just failed.
  if [[ "${SAMPLE_FAILED:-0}" == "1" ]]; then
    warn "Nothing is cached, because the fetch above did not succeed. Once the
network is available, run:"
  else
    warn "Nothing is cached yet. Re-run with --with-sample, or:"
  fi
  echo "    cd ${HERE} && ${VENV_PY} -m onset_hfo.cli fetch --subject sub-01 --t-start 0 --t-stop 60"
  echo
  echo "  You can also open a recording of your own without any of this:"
  echo "    ${LAUNCH} --open /path/to/recording.edf"
fi
echo "Research prototype — not a medical device. See docs/LIMITATIONS.md."
